### ISSUE TITLE
Explicitly set the version?

### ISSUE THREAD

**Issue by chenrui333** [mpalmer/action-validator#62]
👋 it looks like the project is currently using `0.0.0-git` for cargo.toml, what is the rationale behind? (why not just explicitly specify the version) Thanks!

**Comment by mpalmer** [comment]
Because I use git tags to indicate versions instead.  Duplicating information is pointless.  However, Cargo doesn't support not having a version field, nor does it support reading version information out of git tags, and so we have this unsatisfactory compromise solution.

Releases get a (mangled) `Cargo.toml` that properly includes the version number, which is done in [this action step](https://github.com/mpalmer/action-validator/blob/main/.github/workflows/release.yml#L102).
