### ISSUE TITLE
Anchors aren't allowed in workflow definitions

### ISSUE THREAD

**Issue by iainlane** [mpalmer/action-validator#7]
My workflow had some parameters like this:

```
          issue-ignore-any-labels: &exemptLabels |
            pinned
            security
            type/security
            keepalive
          pull-request-ignore-any-labels: *exemptLabels
```

GitHub sadly rejects this, because it isn't using full YAML. ([See here](https://github.community/t/support-for-yaml-anchors/16128))

But `action-validator` accepts this action:

```
laney@melton(:a0e851fcf4|…)> action-validator --verbose .github/workflows/stale.yml
Treating .github/workflows/stale.yml as a Workflow definition
laney@melton(:a0e851fcf4|…)> echo $?
0
```

probably a tough one, as this isn't about the schema but not accepting conformant YAML!

**Comment by mpalmer** [comment]
Oh, yeah, I've been bitten by this one as well.  Have to duplicate long lists of include/exclude paths in all my action triggers, very tedious.

As you say, this is likely to be a tough one, as I wouldn't be surprised if by the time the YAML is finished being parsed, the anchors have been dereferenced and there's no indication that there ever *was* an anchor.

**Comment by mpalmer** [comment]
I've taken a brief look at this issue today, and it looks like, indeed, that anchors do indeed get dereferenced inside the YAML parser, so `action-validator` can't tell there ever was an anchor, and there's no way to ask the YAML parser to not support anchors (because to do that is bonkers, obvs).  I surfaced [this issue](https://github.com/actions/runner/issues/1182) which appears to the canonical place to whinge about a lack of support for anchors, and has some backstory as to *why* they're not supported, a very half-hearted commitment over a year ago from someone at GitHub to do something about it, and some possible workarounds.  In the meantime, I'm just going to have to close this issue as "practically impossible to support", sadly.
